### PR TITLE
added live chat

### PR DESCRIPTION
**Pull request by gfellah45**
- added WhatsApp chat

### CODE REVIEW

**Comment by georgeokez** [comment]
Can you highlight where exactly you added the live chat

**Comment by gfellah45** [comment]
> Can you highlight where exactly you added the live chat

> the script file Is at line 729 and the chat portal line 714

**Comment by gfellah45** [comment]
the script file is at line 729 and chats portal line 714

**Comment by georgeokez** [comment]
Jerry comment out the old chat, if your check the website, the new one is behind it.

**Pull request merged**
